### ISSUE TITLE
Monitoring client fails with 'Temporary failure in name resolution'

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/monitoring#10]
The logs contain multiple instances of

```
Could not establish connection to http://status.outernet.is/heartbeat/v1/: <urlopen error [Errno -3] Temporary failure in name resolution>
```

Forum thread: [here](http://discuss.outernet.is/t/after-restating-the-orxpi-the-monitoring-doesnt-get-started-automatically/1796)
Possibly relevant: [SO question](http://stackoverflow.com/questions/8356517/permanent-temporary-failure-in-name-resolution-after-running-for-a-number-of-h)

**Comment by goodbadwolf** [comment]
Closed due to lack of info & non-reproduction.
